Parameters:
 # test-bucket-long2
 MyBucketName:
   Description: test-bucket-long2
   Type: String
Resources:
 WebsiteBucket:
   Type: AWS::S3::Bucket
   Properties:
     BucketName: !Sub "${MyBucketName}"
     AccessControl: PublicRead
     WebsiteConfiguration:
       IndexDocument: index.html
       ErrorDocument: error.html
     PublicAccessBlockConfiguration:
       BlockPublicAcls: true
     OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
 WebsiteBucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
     Bucket: !Ref 'WebsiteBucket'
     PolicyDocument:
       Statement:
       - Sid: PublicReadGetBucketObjects
         Effect: Allow
         Principal: '*'
         Action: s3:GetObject
         Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]